steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/kube-tut-server',
        '-f',
        'Dockerfile',
        '.',
      ]
